# Generated by Django 5.1.6 on 2025-04-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_consulta_paciente'),
        ('consultas', '0002_alter_consulta_paciente'),
        ('users', '0002_paciente_medico_responsavel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
