# Generated by Django 5.2 on 2025-04-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_observacaosaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('andar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andares.andar')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto', to='pacientes.paciente')),
            ],
            options={
                'unique_together': {('andar', 'numero')},
            },
        ),
    ]
