# Generated by Django 5.2 on 2025-04-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andares', '0001_initial'),
        ('pacientes', '0003_observacaosaude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andar',
            options={'ordering': ['numero'], 'verbose_name': 'Andar', 'verbose_name_plural': 'Andares'},
        ),
        migrations.AlterModelOptions(
            name='quarto',
            options={'ordering': ['andar__numero', 'numero'], 'verbose_name': 'Quarto', 'verbose_name_plural': 'Quartos'},
        ),
        migrations.AddField(
            model_name='quarto',
            name='data_ocupacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ocupação'),
        ),
        migrations.AlterField(
            model_name='andar',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='andar',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número do Andar'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='andar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='andares.andar'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número do Quarto'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto', to='pacientes.paciente', verbose_name='Paciente Internado'),
        ),
    ]
