# Generated by Django 5.1.6 on 2025-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('principio_ativo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
