# Generated by Django 5.1.6 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Lista de medicamentos e dosagens prescritos', null=True),
        ),
    ]
