# Generated by Django 5.1.6 on 2025-04-28 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_medicamentos'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField()),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('medicacao', 'Medicação'), ('sintoma', 'Sintoma'), ('evolucao', 'Evolução'), ('outro', 'Outro')], max_length=50)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Observação de Saúde',
                'verbose_name_plural': 'Observações de Saúde',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
