# Generated by Django 5.1.6 on 2025-05-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacaosaude',
            name='autor',
        ),
        migrations.AddField(
            model_name='observacaosaude',
            name='autor_enfermeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes_feitas', to='users.enfermeiro'),
        ),
        migrations.AddField(
            model_name='observacaosaude',
            name='autor_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes_feitas', to='users.medico'),
        ),
    ]
