# Generated by Django 5.2 on 2025-04-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('historico', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta de Retorno'), ('EXAME', 'Exame de Acompanhamento'), ('MEDICAMENTO', 'Controle de Medicação'), ('OUTRO', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('data_lembrete', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('concluido', models.BooleanField(default=False)),
                ('prioridade', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.paciente')),
            ],
            options={
                'ordering': ['-prioridade', 'data_lembrete'],
            },
        ),
    ]
